### ISSUE TITLE
由于目标计算机积极拒绝，无法连接。 (127.0.0.1:10809)

### ISSUE THREAD

**Issue by deepblue1212** [ybjy82/LearningFucker#60]
由于目标计算机积极拒绝，无法连接。 (127.0.0.1:10809)
user **    login failed!

请大佬看看

**Comment by LFTEC** [comment]
哥们，你这是开着翻墙吧，你的翻墙有问题，还是v2rayn

deepPPP ***@***.***> 于 2024年1月13日周六 14:17写道：
